name: Depoly Docs

on: 
  push:
    branches:
      - main


jobs: 
  build-and-deploy:
    rund-on: ubunt-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Setup Node.js
        uses: action/setup-node@v3
        with:
          node-version: 18


      - run: npm ci

      - run: npm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env: 
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}